#!/bin/sh
#-
# Copyright (c) 2016 Bartek Rutkowski
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

BSDCFG_SHARE="/usr/share/bsdconfig"
. $BSDCFG_SHARE/common.subr || exit 1

: ${BSDDIALOG_OK=0}

echo -n > $BSDINSTALL_TMPETC/rc.conf.hardening
echo -n > $BSDINSTALL_TMPETC/sysctl.conf.hardening
echo -n > $BSDINSTALL_TMPBOOT/loader.conf.hardening

exec 3>&1
FEATURES=$( bsddialog --backtitle "$OSNAME Installer" \
    --title "System Hardening" --nocancel --separate-output \
    --checklist "Choose system security hardening options:" \
    0 0 0 \
	"0 hide_jail" "Hide processes running in jails" ${hide_jail:-off} \
	"1 shm_use_phys" "Lock shared memory pages" ${shm_use_phys:-off} \
	"2 unprivileged_mlock" "Do not allow non-root users to call mlock" ${unprivileged_mlock:-off} \
	"3 clear_tmp" "Clean the /tmp filesystem on system startup" ${clear_tmp:-off} \
	"4 disable_syslogd" "Disable opening Syslogd network socket (disables remote logging)" ${disable_syslogd:-off} \
	"5 secure_console" "Enable console password prompt" ${secure_console:-off} \
	"6 disable_ddtrace" "Disallow DTrace destructive-mode" ${disable_ddtrace:-off} \
	"7 enable_firewall" "Enable a basic firewall (see: /etc/rc.conf)" ${enable_firewall:-off} \
2>&1 1>&3 )
retval=$?
exec 3>&-

if [ $retval -ne $BSDDIALOG_OK ]; then
	exit 1
fi

for feature in $FEATURES; do
	case "$feature" in
	hide_jail)
		echo security.bsd.see_jail_proc=0 >> $BSDINSTALL_TMPETC/sysctl.conf.hardening
		;;
	shm_use_phys)
		echo kern.ipc.shm_use_phys=1 >> $BSDINSTALL_TMPETC/sysctl.conf.hardening
		;;
	unprivileged_mlock)
		echo security.bsd.unprivileged_mlock=0 >> $BSDINSTALL_TMPETC/sysctl.conf.hardening
		;;
	clear_tmp)
		echo 'clear_tmp_enable="YES"' >> $BSDINSTALL_TMPETC/rc.conf.hardening
		;;
	disable_syslogd)
		echo 'syslogd_flags="-ss"' >> $BSDINSTALL_TMPETC/rc.conf.hardening
		;;
	secure_console)
		sed "s/unknown	off secure/unknown	off insecure/g" $BSDINSTALL_CHROOT/etc/ttys > $BSDINSTALL_TMPETC/ttys.hardening
		;;
	disable_ddtrace)
		echo 'security.bsd.allow_destructive_dtrace=0' >> $BSDINSTALL_TMPBOOT/loader.conf.hardening
		;;
	enable_firewall)
		cat >>$BSDINSTALL_TMPETC/rc.conf.hardening <<EOF
firewall_enable="YES"
firewall_type="workstation"
#firewall_myservices="22/tcp"
#firewall_allowservices="fc00::/7 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
firewall_quiet="YES"
firewall_logdeny="YES"
EOF
		;;
	esac
done
