PACKAGE=	hardenedbsd

SCRIPTS=	hbsd-update hbsd-update-build
MAN=		hbsd-update.8 hbsd-update-build.8

CONFS=		hbsd-update.conf hbsd-update.tor.conf
CONFSDIR=	/etc
CONFSMODE=	644

.include <bsd.prog.mk>
